apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Binding
metadata:
  name: overview-binding
  namespace: development
spec:
  instanceRef:
    name: overview-instance
  secretName: overview-credentials
